a = {1, 2, 3}
b = {3, 4, 5}

print(a | b) # UNIAO NO CONJUNTO A E B (PERCEBA QUE O 3 NAO SE REPETIU POIS É UM CONJUNTO QUE NAO HA DUPLICADAS)
print(a & b) # INTERCESSAO TRAZER ELEMENTOS QUE TEM EM COMUM ENTRE A E B
print(a - b) # DIFERENÇA SÓ ELEMENTOS EXCLUSIVOS DOS CONJUNTOS